# Generated by Django 5.0.6 on 2024-06-05 12:33

import django.db.models.deletion
import image_cropping.fields
import testing.models
import testing.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default=None, max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fr', models.CharField(max_length=100)),
                ('nom_ar', models.CharField(max_length=100)),
                ('ministere_fr', models.CharField(max_length=100)),
                ('ministere_ar', models.CharField(max_length=100)),
                ('logo', models.FileField(blank=True, null=True, upload_to='logos/', validators=[testing.models.validate_image_or_svg])),
            ],
        ),
        migrations.CreateModel(
            name='Exams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datedebut', models.DateField()),
                ('datefin', models.DateField()),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='extra_session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_debut', models.CharField(blank=True, max_length=5, null=True)),
                ('heure_fin', models.CharField(blank=True, max_length=5, null=True)),
                ('date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20, unique=True)),
                ('prix_heure', models.IntegerField()),
                ('couleur', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_du_group', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='JourFeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datedebut', models.DateField()),
                ('datefin', models.DateField()),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaxHeureSup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_charge', models.PositiveIntegerField()),
                ('max_supp', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('credit', models.IntegerField()),
                ('coefficient', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20, null=True)),
                ('full_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SalleType', models.CharField(choices=[('AMPHI', 'Amphitheatre'), ('TP', 'Salle Tp'), ('TD', 'Salle Td')], default='Amphitheatre', max_length=20)),
                ('SalleName', models.CharField(max_length=50)),
                ('SalleCapacity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_academique', models.CharField(max_length=9, validators=[testing.validators.validate_academic_year_format, testing.models.validate_academic_year_current])),
                ('numero_de_semestre', models.IntegerField(choices=[(1, '1'), (2, '2')], default=1)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='sessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_debut', models.CharField(blank=True, max_length=5, null=True)),
                ('heure_fin', models.CharField(blank=True, max_length=5, null=True)),
                ('selectedDay', models.CharField(blank=True, choices=[('Samedi', 'Samedi'), ('Dimanche', 'Dimanche'), ('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi')], default='Dimanche', max_length=10, null=True)),
                ('date', models.DateField(null=True)),
                ('is_heure_sup', models.BooleanField(default=True)),
                ('is_partially_heure_sup', models.BooleanField(default=False)),
                ('duration_charge', models.IntegerField(blank=True, null=True)),
                ('duration_sup', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='null', max_length=20)),
                ('SpecAbrev', models.CharField(default='null', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datedebut', models.DateField()),
                ('datefin', models.DateField()),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Type_seance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(choices=[('Enseignant', 'Enseignant'), ('Administrateur', 'Administrateur')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datedebut', models.DateField()),
                ('datefin', models.DateField()),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField()),
                ('month', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('Duration_sup', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Weekly_session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='weekly_session_new',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_debut', models.CharField(blank=True, max_length=5, null=True)),
                ('heure_fin', models.CharField(blank=True, max_length=5, null=True)),
                ('selectedDay', models.CharField(blank=True, choices=[('Samedi', 'Samedi'), ('Dimanche', 'Dimanche'), ('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi')], default='Dimanche', max_length=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='admin',
            name='user',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='phone_number',
            new_name='numero_telephone',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
        migrations.AddField(
            model_name='customuser',
            name='Photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='RIB',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='UserType',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='annee',
            field=models.IntegerField(choices=[(1923, '1923'), (1924, '1924'), (1925, '1925'), (1926, '1926'), (1927, '1927'), (1928, '1928'), (1929, '1929'), (1930, '1930'), (1931, '1931'), (1932, '1932'), (1933, '1933'), (1934, '1934'), (1935, '1935'), (1936, '1936'), (1937, '1937'), (1938, '1938'), (1939, '1939'), (1940, '1940'), (1941, '1941'), (1942, '1942'), (1943, '1943'), (1944, '1944'), (1945, '1945'), (1946, '1946'), (1947, '1947'), (1948, '1948'), (1949, '1949'), (1950, '1950'), (1951, '1951'), (1952, '1952'), (1953, '1953'), (1954, '1954'), (1955, '1955'), (1956, '1956'), (1957, '1957'), (1958, '1958'), (1959, '1959'), (1960, '1960'), (1961, '1961'), (1962, '1962'), (1963, '1963'), (1964, '1964'), (1965, '1965'), (1966, '1966'), (1967, '1967'), (1968, '1968'), (1969, '1969'), (1970, '1970'), (1971, '1971'), (1972, '1972'), (1973, '1973'), (1974, '1974'), (1975, '1975'), (1976, '1976'), (1977, '1977'), (1978, '1978'), (1979, '1979'), (1980, '1980'), (1981, '1981'), (1982, '1982'), (1983, '1983'), (1984, '1984'), (1985, '1985'), (1986, '1986'), (1987, '1987'), (1988, '1988'), (1989, '1989'), (1990, '1990'), (1991, '1991'), (1992, '1992'), (1993, '1993'), (1994, '1994'), (1995, '1995'), (1996, '1996'), (1997, '1997'), (1998, '1998'), (1999, '1999'), (2000, '2000'), (2001, '2001'), (2002, '2002'), (2003, '2003'), (2004, '2004'), (2005, '2005'), (2006, '2006'), (2007, '2007'), (2008, '2008'), (2009, '2009'), (2010, '2010'), (2011, '2011'), (2012, '2012'), (2013, '2013'), (2014, '2014'), (2015, '2015'), (2016, '2016'), (2017, '2017'), (2018, '2018'), (2019, '2019'), (2020, '2020'), (2021, '2021'), (2022, '2022'), (2023, '2023'), (2024, '2024')], default=1),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ccp',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='charge_actuel',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cle',
            field=models.CharField(max_length=2, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cropping',
            field=image_cropping.fields.ImageRatioField('Photo_profil', '300x300', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=False, verbose_name='cropping'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='education',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='heure_sup_actuel',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='jour',
            field=models.IntegerField(choices=[(1, '1 days'), (2, '2 days'), (3, '3 days'), (4, '4 days'), (5, '5 days'), (6, '6 days'), (7, '7 days'), (8, '8 days'), (9, '9 days'), (10, '10 days'), (11, '11 days'), (12, '12 days'), (13, '13 days'), (14, '14 days'), (15, '15 days'), (16, '16 days'), (17, '17 days'), (18, '18 days'), (19, '19 days'), (20, '20 days'), (21, '21 days'), (22, '22 days'), (23, '23 days'), (24, '24 days'), (25, '25 days'), (26, '26 days'), (27, '27 days'), (28, '28 days'), (29, '29 days'), (30, '30 days')], default=1986),
        ),
        migrations.AddField(
            model_name='customuser',
            name='mois',
            field=models.CharField(choices=[('01', 'Janvier'), ('02', 'Février'), ('03', 'Mars'), ('04', 'Avril'), ('05', 'Mai'), ('06', 'Juin'), ('07', 'Juillet'), ('08', 'Août'), ('09', 'Septembre'), ('10', 'Octobre'), ('11', 'Novembre'), ('12', 'Décembre')], default=1, max_length=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nom',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='prenom',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='reset_password_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='responsable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sexe',
            field=models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme')], default='Homme', max_length=10),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datedebut', models.DateField()),
                ('datefin', models.DateField()),
                ('description', models.CharField(max_length=100)),
                ('is_justified', models.BooleanField(default=False)),
                ('enseignant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='etablissement',
            constraint=models.UniqueConstraint(fields=('nom_fr', 'nom_ar', 'ministere_fr', 'ministere_ar', 'logo'), name='unique_Etablissement_constraint'),
        ),
        migrations.AddField(
            model_name='extra_session',
            name='Departement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testing.departement'),
        ),
        migrations.AddField(
            model_name='extra_session',
            name='enseignant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='grade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testing.grade'),
        ),
        migrations.AddField(
            model_name='extra_session',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='testing.group'),
        ),
        migrations.AddField(
            model_name='extra_session',
            name='module',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='testing.module'),
        ),
        migrations.AddField(
            model_name='promo',
            name='departement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testing.departement'),
        ),
        migrations.AddField(
            model_name='module',
            name='promo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.promo'),
        ),
        migrations.AddField(
            model_name='extra_session',
            name='Promo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testing.promo'),
        ),
        migrations.AddField(
            model_name='report',
            name='sender',
            field=models.ForeignKey(limit_choices_to={'is_admin': False}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salle',
            name='departement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.departement'),
        ),
        migrations.AddField(
            model_name='extra_session',
            name='salle',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='testing.salle'),
        ),
        migrations.AddField(
            model_name='section',
            name='promo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.promo'),
        ),
        migrations.AddField(
            model_name='group',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.section'),
        ),
        migrations.AddField(
            model_name='extra_session',
            name='Section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testing.section'),
        ),
        migrations.AddConstraint(
            model_name='semestre',
            constraint=models.UniqueConstraint(fields=('annee_academique', 'numero_de_semestre', 'date_debut', 'date_fin'), name='unique_Semestre_constraint'),
        ),
        migrations.AddField(
            model_name='module',
            name='semestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.semestre'),
        ),
        migrations.AddField(
            model_name='extra_session',
            name='semestre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testing.semestre'),
        ),
        migrations.AddField(
            model_name='sessions',
            name='Departement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testing.departement'),
        ),
        migrations.AddField(
            model_name='sessions',
            name='Promo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testing.promo'),
        ),
        migrations.AddField(
            model_name='sessions',
            name='Section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testing.section'),
        ),
        migrations.AddField(
            model_name='sessions',
            name='enseignant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sessions',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='testing.group'),
        ),
        migrations.AddField(
            model_name='sessions',
            name='module',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='testing.module'),
        ),
        migrations.AddField(
            model_name='sessions',
            name='salle',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='testing.salle'),
        ),
        migrations.AddField(
            model_name='sessions',
            name='semestre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testing.semestre'),
        ),
        migrations.AddConstraint(
            model_name='specialite',
            constraint=models.UniqueConstraint(fields=('nom', 'SpecAbrev'), name='unique_Specialite_constraint'),
        ),
        migrations.AddField(
            model_name='promo',
            name='specialite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testing.specialite'),
        ),
        migrations.AddField(
            model_name='sessions',
            name='type_session',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='testing.type_seance'),
        ),
        migrations.AddField(
            model_name='extra_session',
            name='type_session',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='testing.type_seance'),
        ),
        migrations.AddField(
            model_name='week',
            name='sessions',
            field=models.ManyToManyField(to='testing.sessions'),
        ),
        migrations.AddField(
            model_name='weekly_session_new',
            name='Departement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testing.departement'),
        ),
        migrations.AddField(
            model_name='weekly_session_new',
            name='Promo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testing.promo'),
        ),
        migrations.AddField(
            model_name='weekly_session_new',
            name='Section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testing.section'),
        ),
        migrations.AddField(
            model_name='weekly_session_new',
            name='enseignant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='weekly_session_new',
            name='group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='testing.group'),
        ),
        migrations.AddField(
            model_name='weekly_session_new',
            name='module',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='testing.module'),
        ),
        migrations.AddField(
            model_name='weekly_session_new',
            name='salle',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='testing.salle'),
        ),
        migrations.AddField(
            model_name='weekly_session_new',
            name='semestre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testing.semestre'),
        ),
        migrations.AddField(
            model_name='weekly_session_new',
            name='type_session',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='testing.type_seance'),
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.AddConstraint(
            model_name='salle',
            constraint=models.UniqueConstraint(fields=('departement', 'SalleType', 'SalleName', 'SalleCapacity'), name='unique_Salle_constraint'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('promo', 'nom'), name='unique_Section_constraint'),
        ),
        migrations.AddConstraint(
            model_name='group',
            constraint=models.UniqueConstraint(fields=('section', 'numero_du_group'), name='unique_Group_constraint'),
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.UniqueConstraint(fields=('semestre', 'promo', 'nom', 'credit', 'coefficient'), name='unique_Module_constraint'),
        ),
        migrations.AddConstraint(
            model_name='promo',
            constraint=models.UniqueConstraint(fields=('departement', 'nom', 'specialite'), name='unique_promo_constraint'),
        ),
        migrations.AlterUniqueTogether(
            name='sessions',
            unique_together={('enseignant', 'date', 'selectedDay', 'heure_debut', 'heure_fin', 'type_session')},
        ),
        migrations.AlterUniqueTogether(
            name='extra_session',
            unique_together={('enseignant', 'date', 'heure_debut', 'heure_fin', 'type_session')},
        ),
        migrations.AlterUniqueTogether(
            name='week',
            unique_together={('week_number', 'month')},
        ),
        migrations.AlterUniqueTogether(
            name='weekly_session_new',
            unique_together={('enseignant', 'selectedDay', 'heure_debut', 'heure_fin', 'type_session')},
        ),
    ]
