# Generated by Django 5.0.3 on 2024-03-30 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='user',
        ),
        migrations.AddField(
            model_name='customuser',
            name='RIP',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='grade',
            field=models.CharField(blank=True, choices=[('assistant master a', 'Assistant Master A'), ('assistant master b', 'Assistant Master B'), ('lecturer a', 'Lecturer A'), ('lecturer b', 'Lecturer B'), ('teacher', 'Teacher'), ('professor', 'Professor')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_recruited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_responsable',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
