# Generated by Django 5.0.6 on 2024-06-05 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_departement_etablissement_exams_extra_session_grade_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Weekly_session',
        ),
    ]
