# Generated by Django 5.0.3 on 2024-05-01 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_departement_semestre_specialite_usertype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='education',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
