# Generated by Django 5.0.3 on 2024-05-20 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_departement_etablissement_exams_grade_jourferies_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Weekly_session',
        ),
    ]
