# Generated by Django 5.0.3 on 2024-05-03 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_departement_semestre_specialite_usertype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('prix_heure', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='exams',
            name='enseignant',
        ),
        migrations.RemoveField(
            model_name='jourferies',
            name='enseignant',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='enseignant',
        ),
        migrations.RemoveField(
            model_name='vacation',
            name='enseignant',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='UserType',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='grade',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='testing.grade'),
        ),
    ]
