# Generated by Django 5.0.6 on 2024-05-18 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_departement_etablissement_exams_grade_jourferies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessions',
            name='charge_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessions',
            name='is_heure_sup',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sessions',
            name='is_partially_heure_sup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sessions',
            name='sup_duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
