# Generated by Django 5.0.3 on 2024-04-27 15:27

import django.db.models.deletion
import testing.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_absence_exams_jourferies_stage_vacation_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('Cycle préparatoire', 'Cycle préparatoire'), ('Cycle supérieur', 'Cycle supérieur')], default='Cycle préparatoire', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee_academique', models.CharField(max_length=9, validators=[testing.validators.validate_academic_year_format])),
                ('numero_de_semestre', models.IntegerField(choices=[(1, '1'), (2, '2')], default=1)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='null', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(choices=[('Enseignant', 'Enseignant'), ('Administrateur', 'Administrateur')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20, null=True)),
                ('departement', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testing.departement')),
                ('specialite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testing.specialite')),
            ],
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_salle', models.CharField(choices=[('AMPHI', 'Amphitheatre'), ('TP', 'Salle Tp'), ('TD', 'Salle Td')], default='Amphitheatre', max_length=20)),
                ('nom_salle', models.CharField(max_length=50)),
                ('capacity', models.PositiveIntegerField()),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.departement')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=1)),
                ('promo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.promo')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('credit', models.IntegerField()),
                ('coefficient', models.IntegerField()),
                ('promo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.promo')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.semestre')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_du_group', models.IntegerField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.section')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.semestre')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='UserType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testing.usertype'),
        ),
        migrations.CreateModel(
            name='Weekly_session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('1', 'Dimanche'), ('2', 'Lundi'), ('3', 'Mardi'), ('4', 'Mercredi'), ('5', 'Jeudi')], default='Dimanche', max_length=10)),
                ('heure_debut', models.IntegerField()),
                ('heure_fin', models.IntegerField()),
                ('session_type', models.CharField(choices=[('1', 'Cours'), ('2', 'TD'), ('3', 'TP')], default='Cours', max_length=10)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.group')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.module')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testing.salle')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
