# Generated by Django 5.0.3 on 2024-05-01 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_alter_customuser_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='grade',
            field=models.CharField(blank=True, choices=[('assistant master a', 'assistant master a'), ('assistant master b', 'assistant master b'), ('lecteur a', 'lecteur a'), ('lecteur b', 'lecteur b'), ('enseignant', 'enseignant'), ('professeur', 'professeur')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='mois',
            field=models.CharField(choices=[('01', 'Janvier'), ('02', 'Février'), ('03', 'Mars'), ('04', 'Avril'), ('05', 'Mai'), ('06', 'Juin'), ('07', 'Juillet'), ('08', 'Août'), ('09', 'Septembre'), ('10', 'Octobre'), ('11', 'Novembre'), ('12', 'Décembre')], default=1, max_length=10),
        ),
    ]
