# Generated by Django 5.0.3 on 2024-05-03 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_grade_remove_exams_enseignant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='grade',
            field=models.CharField(blank=True, choices=[('assistant master a', 'assistant master a'), ('assistant master a', 'assistant master b'), ('lecteur a', 'lecteur a'), ('lecteur b', 'lecteur b'), ('enseignant', 'enseignant'), ('professeur', 'professeur')], max_length=50, null=True),
        ),
    ]
