# Generated by Django 5.0.3 on 2024-05-20 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_delete_weekly_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weekly_session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selectedOption', models.CharField(choices=[('Que pour une semaine', 'Que pour une semaine'), ('Pour le semestre', 'Pour le semestre')], default='Que pour une semaine', max_length=20)),
                ('selectedDay', models.CharField(blank=True, max_length=10, null=True)),
                ('heure_supp', models.BooleanField(default=False)),
                ('heure_debut', models.CharField(blank=True, max_length=10, null=True)),
                ('heure_fin', models.CharField(blank=True, max_length=10, null=True)),
                ('Departement', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testing.departement')),
                ('Promo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testing.promo')),
                ('Section', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testing.section')),
                ('Semestre', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testing.semestre')),
                ('enseignant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='testing.group')),
                ('module', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='testing.module')),
                ('salle', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='testing.salle')),
                ('type_session', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='testing.type_seance')),
            ],
        ),
    ]
