# Generated by Django 5.0.3 on 2024-04-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_absence_exams_jourferies_stage_vacation_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='RIP',
        ),
        migrations.AddField(
            model_name='absence',
            name='is_justified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='payemnt_info',
            field=models.CharField(choices=[('rib', 'RIB'), ('ccp clé', 'Ccp Clé')], max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='grade',
            field=models.CharField(blank=True, choices=[('assistant master a', 'Assistant Master A'), ('assistant master b', 'Assistant Master B'), ('lecteur a', 'Lecteur A'), ('lecteur b', 'Lecteur B'), ('enseignant', 'Enseignant'), ('professeur', 'Professeur')], max_length=50, null=True),
        ),
    ]
