# Generated by Django 5.0.6 on 2024-06-05 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_delete_weekly_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='cropping',
        ),
    ]
