# Generated by Django 5.0.3 on 2024-05-03 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0004_alter_customuser_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='grade',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='testing.grade'),
        ),
    ]
