# Generated by Django 5.0.6 on 2024-06-05 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0004_remove_customuser_cropping'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoHeureSup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_charge_cours', models.PositiveIntegerField()),
                ('max_charge_td', models.PositiveIntegerField()),
                ('unit', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='MaxHeureSup',
        ),
    ]
