# Generated by Django 5.0.3 on 2024-05-20 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0004_weekly_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salle',
            old_name='capacite',
            new_name='SalleCapacity',
        ),
        migrations.RenameField(
            model_name='salle',
            old_name='nom_salle',
            new_name='SalleName',
        ),
        migrations.RenameField(
            model_name='salle',
            old_name='type_salle',
            new_name='SalleType',
        ),
    ]
