# Generated by Django 5.0.3 on 2024-05-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0005_alter_customuser_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekly_session',
            name='heure_debut',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weekly_session',
            name='heure_fin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
