# Generated by Django 5.0.6 on 2024-06-05 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0005_infoheuresup_delete_maxheuresup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infoheuresup',
            old_name='unit',
            new_name='Coef',
        ),
    ]
