# Generated by Django 5.0.3 on 2024-05-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0005_rename_capacite_salle_sallecapacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salle',
            name='SalleType',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
