# Generated by Django 5.0.3 on 2024-05-05 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0006_alter_weekly_session_heure_debut_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type_seance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=15)),
            ],
        ),
        migrations.RenameField(
            model_name='weekly_session',
            old_name='jour',
            new_name='selectedDay',
        ),
        migrations.RenameField(
            model_name='weekly_session',
            old_name='pour',
            new_name='selectedOption',
        ),
        migrations.RemoveField(
            model_name='weekly_session',
            name='date',
        ),
        migrations.AlterField(
            model_name='weekly_session',
            name='type_session',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='testing.type_seance'),
        ),
    ]
