# Generated by Django 5.0.3 on 2024-05-20 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0006_alter_salle_salletype'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialite',
            name='SpecName',
            field=models.CharField(default='null', max_length=20),
        ),
    ]
