# Generated by Django 5.0.3 on 2024-05-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0007_type_seance_rename_jour_weekly_session_selectedday_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fr', models.CharField(max_length=100)),
                ('nom_ar', models.CharField(max_length=100)),
                ('ministere_fr', models.CharField(max_length=100)),
                ('ministere_ar', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='Photo_profil',
            field=models.ImageField(blank=True, null=True, upload_to='photo_profil/'),
        ),
    ]
