# Generated by Django 5.0.3 on 2024-04-30 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0004_remove_customuser_rip_absence_is_justified_and_more'),
        ('testing', '0007_alter_customuser_gender'),
    ]

    operations = [
    ]
