# Generated by Django 5.0.3 on 2024-05-20 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0007_specialite_specname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specialite',
            old_name='SpecName',
            new_name='SpecAbrev',
        ),
    ]
