# Generated by Django 5.0.6 on 2024-05-21 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0008_rename_specname_specialite_specabrev'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salle',
            name='SalleType',
            field=models.CharField(choices=[('AMPHI', 'Amphitheatre'), ('TP', 'Salle Tp'), ('TD', 'Salle Td')], default='Amphitheatre', max_length=20),
        ),
        migrations.CreateModel(
            name='extra_session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_debut', models.CharField(blank=True, max_length=5, null=True)),
                ('heure_fin', models.CharField(blank=True, max_length=5, null=True)),
                ('date', models.DateField(null=True)),
                ('Departement', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testing.departement')),
                ('Promo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testing.promo')),
                ('Section', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testing.section')),
                ('enseignant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='testing.group')),
                ('module', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='testing.module')),
                ('salle', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='testing.salle')),
                ('semestre', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testing.semestre')),
                ('type_session', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='testing.type_seance')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='sessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_debut', models.CharField(blank=True, max_length=5, null=True)),
                ('heure_fin', models.CharField(blank=True, max_length=5, null=True)),
                ('selectedDay', models.CharField(blank=True, choices=[('Samedi', 'Samedi'), ('Dimanche', 'Dimanche'), ('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi')], default='Dimanche', max_length=10, null=True)),
                ('date', models.DateField(null=True)),
                ('is_heure_sup', models.BooleanField(default=True)),
                ('is_partially_heure_sup', models.BooleanField(default=False)),
                ('duration_charge', models.IntegerField(blank=True, null=True)),
                ('duration_sup', models.IntegerField(blank=True, null=True)),
                ('Departement', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testing.departement')),
                ('Promo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testing.promo')),
                ('Section', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testing.section')),
                ('enseignant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='testing.group')),
                ('module', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='testing.module')),
                ('salle', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='testing.salle')),
                ('semestre', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testing.semestre')),
                ('type_session', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='testing.type_seance')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='weekly_session_new',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure_debut', models.CharField(blank=True, max_length=5, null=True)),
                ('heure_fin', models.CharField(blank=True, max_length=5, null=True)),
                ('selectedDay', models.CharField(blank=True, choices=[('Samedi', 'Samedi'), ('Dimanche', 'Dimanche'), ('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi')], default='Dimanche', max_length=10, null=True)),
                ('Departement', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testing.departement')),
                ('Promo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testing.promo')),
                ('Section', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testing.section')),
                ('enseignant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='testing.group')),
                ('module', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='testing.module')),
                ('salle', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='testing.salle')),
                ('semestre', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testing.semestre')),
                ('type_session', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='testing.type_seance')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
