# Generated by Django 5.0.3 on 2024-05-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0008_etablissement_customuser_photo_profil'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaxHeureSup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_charge', models.PositiveIntegerField()),
                ('max_supp', models.PositiveIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='grade',
            name='couleur',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
