# Generated by Django 5.0.3 on 2024-05-10 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0009_maxheuresup_grade_couleur'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
