# Generated by Django 5.0.3 on 2024-04-30 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0009_remove_customuser_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reset_password_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
