# Generated by Django 5.0.6 on 2024-05-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0009_alter_salle_salletype_extra_session_sessions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField()),
                ('month', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('sessions', models.ManyToManyField(to='testing.sessions')),
            ],
        ),
    ]
