# Generated by Django 5.0.3 on 2024-04-30 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0011_alter_customuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
