# Generated by Django 5.0.3 on 2024-05-13 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0011_alter_customuser_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weekly_session',
            name='semestre',
        ),
        migrations.AddField(
            model_name='weekly_session',
            name='Semestre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testing.semestre'),
        ),
    ]
