# Generated by Django 5.0.3 on 2024-05-13 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0012_remove_weekly_session_semestre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekly_session',
            name='heure_debut',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='weekly_session',
            name='heure_fin',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='weekly_session',
            name='selectedDay',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
