# Generated by Django 5.0.3 on 2024-04-30 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0012_remove_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='RIB',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
