# Generated by Django 5.0.3 on 2024-04-30 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0013_customuser_rib'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ccp',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cle',
            field=models.CharField(max_length=2, null=True, unique=True),
        ),
    ]
